/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package metodos_numericos;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vito-dante
 */
public class Interfaz_grafica extends javax.swing.JFrame {
    
            private String tamano;
            private int tconvertido;
            validacion probar=new validacion();
            
            
                
                
    /**
     * Creates new form Interfaz_grafica
     */
    public Interfaz_grafica() {
       
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        Var = new javax.swing.JTextField();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Math-On-a-Blackboard-Wallpaper-Background.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("De cuantas variables es su sistema?");

        Var.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarActionPerformed(evt);
            }
        });
        Var.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VarKeyPressed(evt);
            }
        });

        buttonAction1.setText("Aceptar");
        buttonAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAction1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Estudiante:");

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Vito Marcilio Marca Vilte");

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(Var, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Var, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAction1ActionPerformed
               
                tamano=Var.getText();

                if(probar.isNumeric(tamano))
                {
                    Var.setText("");
                    tconvertido=Integer.parseInt(tamano);
                    if(tconvertido<1){
                    JOptionPane.showMessageDialog(null,"Los numeros negativos\n y ceros no son validos","Nota",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                            if(tconvertido<101){
                            //probar si es menor 101 porque ese es el tamano del array de la otra clase que va al modelo
                            Matrix_G ecuacion=new Matrix_G();
                            ecuacion.setTdvariable(tconvertido);
                            ecuacion.colocarhead();
                            ecuacion.vistamodel();
                            ecuacion.setVisible(true);
             //               Matrix.vistamodel
                            // NOTA : ELIMINAR TODOS LOS MAIN DE LOS JFRAME
                            /*
                            AQUI HACER UNA CLASS QUE PASE UN PARAMETRO POR EJ : PLANTON("tconvertido");
                            PLANTON SERIA LA CLASE 
                            Caso_Matrix inside2 = new Caso_Matrix();
                            inside2.setVisible(true);*/
                            }
                            else{
                                JOptionPane.showMessageDialog(null,"Solo se puede \n ingresar hasta el 100","Nota",JOptionPane.ERROR_MESSAGE);
                            }
                        }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Caracter no valido\n Ingresar solo numeros","Nota",JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_buttonAction1ActionPerformed

    private void VarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VarKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        Matrix_G ecuacion=new Matrix_G();
                tamano=Var.getText();

                if(probar.isNumeric(tamano))
                {
                    Var.setText("");
                    tconvertido=Integer.parseInt(tamano);
                    if(tconvertido<1){
                    JOptionPane.showMessageDialog(null,"Los numeros negativos\n y ceros no son validos","Nota",JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                            if(tconvertido<101){
                            //probar si es menor 101 porque ese es el tamano del array de la otra clase que va al modelo
                            ecuacion.setTdvariable(tconvertido);
                            ecuacion.colocarhead();
                            ecuacion.vistamodel();
                            ecuacion.setVisible(true);
             //               Matrix.vistamodel
                            // NOTA : ELIMINAR TODOS LOS MAIN DE LOS JFRAME
                            /*
                            AQUI HACER UNA CLASS QUE PASE UN PARAMETRO POR EJ : PLANTON("tconvertido");
                            PLANTON SERIA LA CLASE 
                            Caso_Matrix inside2 = new Caso_Matrix();
                            inside2.setVisible(true);*/
                            }
                            else{
                                JOptionPane.showMessageDialog(null,"Solo se puede \n ingresar hasta el 100","Nota",JOptionPane.ERROR_MESSAGE);
                            }
                        }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Caracter no valido\n Ingresar solo numeros","Nota",JOptionPane.ERROR_MESSAGE);   
                }
       
       }
        
    }//GEN-LAST:event_VarKeyPressed

    private void VarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Var;
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
