package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String ciC;
     private String nombreC;
     private String apellidoC;
     private String telefonoC;
     private String direccionC;
     private Set salidaProductos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String ciC) {
        this.ciC = ciC;
    }
    public Cliente(String ciC, String nombreC, String apellidoC, String telefonoC, String direccionC, Set salidaProductos) {
       this.ciC = ciC;
       this.nombreC = nombreC;
       this.apellidoC = apellidoC;
       this.telefonoC = telefonoC;
       this.direccionC = direccionC;
       this.salidaProductos = salidaProductos;
    }
   
    public String getCiC() {
        return this.ciC;
    }
    
    public void setCiC(String ciC) {
        this.ciC = ciC;
    }
    public String getNombreC() {
        return this.nombreC;
    }
    
    public void setNombreC(String nombreC) {
        this.nombreC = nombreC;
    }
    public String getApellidoC() {
        return this.apellidoC;
    }
    
    public void setApellidoC(String apellidoC) {
        this.apellidoC = apellidoC;
    }
    public String getTelefonoC() {
        return this.telefonoC;
    }
    
    public void setTelefonoC(String telefonoC) {
        this.telefonoC = telefonoC;
    }
    public String getDireccionC() {
        return this.direccionC;
    }
    
    public void setDireccionC(String direccionC) {
        this.direccionC = direccionC;
    }
    public Set getSalidaProductos() {
        return this.salidaProductos;
    }
    
    public void setSalidaProductos(Set salidaProductos) {
        this.salidaProductos = salidaProductos;
    }




}


