package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private String ciF;
     private RolCargo rolCargo;
     private Estado estado;
     private String nombreF;
     private String apellidoF;
     private String telefonoF;
     private String direccionF;
     private Set usuarios = new HashSet(0);
     private Set salidaProductos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String ciF, RolCargo rolCargo, Estado estado) {
        this.ciF = ciF;
        this.rolCargo = rolCargo;
        this.estado = estado;
    }
    public Funcionario(String ciF, RolCargo rolCargo, Estado estado, String nombreF, String apellidoF, String telefonoF, String direccionF, Set usuarios, Set salidaProductos) {
       this.ciF = ciF;
       this.rolCargo = rolCargo;
       this.estado = estado;
       this.nombreF = nombreF;
       this.apellidoF = apellidoF;
       this.telefonoF = telefonoF;
       this.direccionF = direccionF;
       this.usuarios = usuarios;
       this.salidaProductos = salidaProductos;
    }
   
    public String getCiF() {
        return this.ciF;
    }
    
    public void setCiF(String ciF) {
        this.ciF = ciF;
    }
    public RolCargo getRolCargo() {
        return this.rolCargo;
    }
    
    public void setRolCargo(RolCargo rolCargo) {
        this.rolCargo = rolCargo;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombreF() {
        return this.nombreF;
    }
    
    public void setNombreF(String nombreF) {
        this.nombreF = nombreF;
    }
    public String getApellidoF() {
        return this.apellidoF;
    }
    
    public void setApellidoF(String apellidoF) {
        this.apellidoF = apellidoF;
    }
    public String getTelefonoF() {
        return this.telefonoF;
    }
    
    public void setTelefonoF(String telefonoF) {
        this.telefonoF = telefonoF;
    }
    public String getDireccionF() {
        return this.direccionF;
    }
    
    public void setDireccionF(String direccionF) {
        this.direccionF = direccionF;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getSalidaProductos() {
        return this.salidaProductos;
    }
    
    public void setSalidaProductos(Set salidaProductos) {
        this.salidaProductos = salidaProductos;
    }




}


