package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private Integer idInventario;
     private Integer cantidadStock;
     private Date fechaInv;
     private Set productos = new HashSet(0);

    public Inventario() {
    }

    public Inventario(Integer cantidadStock, Date fechaInv, Set productos) {
       this.cantidadStock = cantidadStock;
       this.fechaInv = fechaInv;
       this.productos = productos;
    }
   
    public Integer getIdInventario() {
        return this.idInventario;
    }
    
    public void setIdInventario(Integer idInventario) {
        this.idInventario = idInventario;
    }
    public Integer getCantidadStock() {
        return this.cantidadStock;
    }
    
    public void setCantidadStock(Integer cantidadStock) {
        this.cantidadStock = cantidadStock;
    }
    public Date getFechaInv() {
        return this.fechaInv;
    }
    
    public void setFechaInv(Date fechaInv) {
        this.fechaInv = fechaInv;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


