package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codProd;
     private Inventario inventario;
     private Estado estado;
     private Categoria categoria;
     private Integer cantidad;
     private String observacion;
     private Date fechaIngreso;
     private Date fechaModificacion;
     private Set salidaProductos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codProd, Inventario inventario, Estado estado, Categoria categoria) {
        this.codProd = codProd;
        this.inventario = inventario;
        this.estado = estado;
        this.categoria = categoria;
    }
    public Producto(String codProd, Inventario inventario, Estado estado, Categoria categoria, Integer cantidad, String observacion, Date fechaIngreso, Date fechaModificacion, Set salidaProductos) {
       this.codProd = codProd;
       this.inventario = inventario;
       this.estado = estado;
       this.categoria = categoria;
       this.cantidad = cantidad;
       this.observacion = observacion;
       this.fechaIngreso = fechaIngreso;
       this.fechaModificacion = fechaModificacion;
       this.salidaProductos = salidaProductos;
    }
   
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getSalidaProductos() {
        return this.salidaProductos;
    }
    
    public void setSalidaProductos(Set salidaProductos) {
        this.salidaProductos = salidaProductos;
    }




}


