package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * RolCargo generated by hbm2java
 */
public class RolCargo  implements java.io.Serializable {


     private Integer idRol;
     private String cargo;
     private String descripcion;
     private Set funcionarios = new HashSet(0);

    public RolCargo() {
    }

    public RolCargo(String cargo, String descripcion, Set funcionarios) {
       this.cargo = cargo;
       this.descripcion = descripcion;
       this.funcionarios = funcionarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


