package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SalidaProducto generated by hbm2java
 */
public class SalidaProducto  implements java.io.Serializable {


     private Integer idSalida;
     private Producto producto;
     private Funcionario funcionario;
     private Cliente cliente;
     private Integer cantidad;
     private Date fecha;

    public SalidaProducto() {
    }

	
    public SalidaProducto(Producto producto, Funcionario funcionario, Cliente cliente) {
        this.producto = producto;
        this.funcionario = funcionario;
        this.cliente = cliente;
    }
    public SalidaProducto(Producto producto, Funcionario funcionario, Cliente cliente, Integer cantidad, Date fecha) {
       this.producto = producto;
       this.funcionario = funcionario;
       this.cliente = cliente;
       this.cantidad = cantidad;
       this.fecha = fecha;
    }
   
    public Integer getIdSalida() {
        return this.idSalida;
    }
    
    public void setIdSalida(Integer idSalida) {
        this.idSalida = idSalida;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


