package MAP;
// Generated Jul 15, 2014 10:25:33 AM by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Estado estado;
     private Funcionario funcionario;
     private String usuario;
     private String password;
     private String rol;

    public Usuario() {
    }

	
    public Usuario(Estado estado, Funcionario funcionario) {
        this.estado = estado;
        this.funcionario = funcionario;
    }
    public Usuario(Estado estado, Funcionario funcionario, String usuario, String password, String rol) {
       this.estado = estado;
       this.funcionario = funcionario;
       this.usuario = usuario;
       this.password = password;
       this.rol = rol;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }




}


