/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGrafica;

import DAO.FuncionarioDAO;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.edisoncor.gui.util.Avatar;

/**
 *
 * @author Vito
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private int ult_usuario;

    /**
     * Creates new form Interfaz_principal
     */
    public InterfazPrincipal() {
        initComponents();
        /*this.ult_usuario=id_us;
         CONSTRUCTOR int id_us, int id_pers
         Persona_acceso funcDAO = new Persona_acceso();
         Persona funcionario = funcDAO.MostrarPersonaPorId(id_pers);
         UsuarioLabel.setText(funcionario.getApellidos()+" "+funcionario.getNombre());*/

        ////////////////////////// CONTENIDO/////////////////////////////////////////
        List avatares = new ArrayList();
        Avatar d = new Avatar("Productos", loadImage("/Imagenes/registroK.png"));
        d.getTitulo();
        avatares.add(new Avatar("Cliente", loadImage("/Imagenes/registroH.png")));
        avatares.add(new Avatar("Funcionario", loadImage("/Imagenes/registroH.png")));
        avatares.add(new Avatar("Producto", loadImage("/Imagenes/registroH.png")));
        avatares.add(new Avatar("Salida Pro", loadImage("/Imagenes/registroK.png")));
        avatares.add(new Avatar("Reg. agua", loadImage("/Imagenes/bottled-water-delivery.png")));
        avatares.add(new Avatar("Reg. Castana", loadImage("/Imagenes/nuez.png")));
        avatares.add(new Avatar("Reg. Fruta", loadImage("/Imagenes/lemon-icon.png")));
        avatares.add(new Avatar("Cerrar Todo", loadImage("/Imagenes/Salir.png")));
        pnlavatar.setAvatars(avatares);
    }

    private static Image loadImage(String fileName) {
        try {
            return ImageIO.read(JFrame.class.getResource(fileName));
        } catch (Exception e) {
            return null;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlavatar = new org.edisoncor.gui.panel.PanelAvatarChooser();
        jPanel1 = new javax.swing.JPanel();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        UsuarioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pnlavatar.setAlignmentX(2.0F);
        pnlavatar.setAlignmentY(2.0F);
        pnlavatar.setPreferredSize(new java.awt.Dimension(800, 909));
        pnlavatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlavatarMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        clockDigital1.setBackground(new java.awt.Color(14, 14, 26));
        clockDigital1.setForeground(new java.awt.Color(0, 153, 153));
        clockDigital1.setFont(new java.awt.Font("Microsoft Sans Serif", 2, 36)); // NOI18N

        UsuarioLabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(clockDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlavatar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlavatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlavatarMouseClicked
        // TODO add your handling code here:
        switch (pnlavatar.getAvatarIndex()) {
            case 0:
                InterfazCliente abrir = new InterfazCliente();
                abrir.setVisible(true);
                break;
            case 1:
                InterfazRegistrarFuncionario funcionario = new InterfazRegistrarFuncionario();
                funcionario.setVisible(true);
                break;
            case 2:
                InterfazRegistrarProducto abrirP=new InterfazRegistrarProducto();
                abrirP.setVisible(true);
                break;
            case 3:
                InterfazSalidaProducto SalidaP = new InterfazSalidaProducto();
                SalidaP.setVisible(true);
                break;
            case 4:

                break;
            case 5:

                break;
            case 6:

                break;
            case 7:
                if (JOptionPane.showConfirmDialog(rootPane, "Estás seguro de Salir?", "Cerrar aplicación", 1) == 0) {
                    System.exit(0);
                }
                break;

        }
    }//GEN-LAST:event_pnlavatarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsuarioLabel;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelAvatarChooser pnlavatar;
    // End of variables declaration//GEN-END:variables
}
